Repository Stacha-dev/tardis, pull requests merged in 2020-12, with the labels that each got.

#35 Set default body content
  src/Lib/Authorization/AuthorizationFactory.php
  src/Lib/Http/Body.php
  tests/Lib/Authorization/AuthorizationTest.php
Labels: bug

#39 Update information in a README
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  README.md
  bin/install.sh
Labels: documentation

#42 Dev exeption
  src/Controller/App.php
Labels: enhancement

#45 Add PNG support
  composer.lock
  src/Controller/Article.php
  src/Controller/File.php
  src/Controller/Gallery.php
  src/Controller/Image.php
  src/Lib/FileSystem/Image.php
  src/Model/Entity/Image.php
Labels: enhancement

#48 Add images folder to repository #44
  .gitignore
  public/index.html
  public/storage/images/.gitkeep
Labels: bug

#49 Feat/issue pr template
  .github/workflows/issue_template.md
  .github/workflows/pull_request_template.md
Labels: enhancement

#53 Fix/image thumbnails generator
  src/Controller/Image.php
  src/Lib/FileSystem/Image.php
Labels: bug

#54 Feat/image state
  src/Controller/Gallery.php
  src/Controller/Image.php
  src/Lib/Http/Body.php
Labels: enhancement

#57 Add PHPStan config
  .gitignore
  composer.json
  composer.lock
  phpstan.neon.dist
Labels: enhancement

#58 Fix/phpstan tests
  phpstan.neon.dist
  tests/Controller/ArticleTest.php
  tests/Controller/BaseTest.php
  tests/Lib/Http/RequestTest.php
Labels: enhancement

#56 hash for passwords
  bin/install.sh
  config/common.ini.tmpl
  phpunit.xml
  src/Controller/User.php
  src/Lib/Security/Hash.php
  tests/Lib/Security/HashTest.php
Labels: enhancement

#63 Fix phpunit codecov
  composer.json
Labels: bug

#64 Update master
  .github/workflows/issue_template.md
  .github/workflows/pull_request_template.md
  .gitignore
  bin/install.sh
  composer.json
  composer.lock
  config/common.ini.tmpl
  phpstan.neon.dist
  phpunit.xml
  public/index.html
  public/storage/images/.gitkeep
  src/Controller/App.php
  src/Controller/Article.php
  src/Controller/File.php
  src/Controller/Gallery.php
  src/Controller/Image.php
  src/Controller/User.php
  src/Lib/FileSystem/Image.php
  src/Lib/Http/Body.php
  src/Lib/Security/Hash.php
  src/Model/Entity/Image.php
  tests/Controller/ArticleTest.php
  tests/Controller/BaseTest.php
  tests/Lib/Http/RequestTest.php
  tests/Lib/Security/HashTest.php
Labels: enhancement

#65 Move templates into right folder
  .github/issue_template.md
  .github/pull_request_template.md
Labels: documentation

#70 Update workflows
  .github/workflows/cd.yml
  .github/workflows/deploy.yml
  .github/workflows/issue_template.md
  .github/workflows/pull_request_template.md
  .github/workflows/test.yml
Labels: enhancement

#73 Feat/user login
  .github/workflows/test.yml
  src/Controller/User.php
Labels: enhancement

#75 Add PHP unit section
  README.md
Labels: documentation

#74 Add DB fixtures and console command
  README.md
  bin/console
  bin/install.sh
  composer.json
  composer.lock
  src/Controller/User.php
  src/Lib/Command/AppPasswordCommand.php
  src/Lib/Command/FixturesLoadCommand.php
  src/Model/Fixtures/User.php
Labels: enhancement

#77 Add phpdoc
  composer.json
  composer.lock
  doxyfile
  phpdoc.dist.xml
Labels: documentation
