Repository Stacha-dev/tardis, pull requests merged in 2021-01, with the labels that each got.

#81 Add gallery thumbnail
  src/Controller/Gallery.php
Labels: enhancement

#83 Order galleries by updated time
  src/Controller/Gallery.php
Labels: enhancement

#88 feat: Add tag entity
  composer.lock
  src/Bootstrap.php
  src/Controller/Gallery.php
  src/Model/Entity/Gallery.php
  src/Model/Entity/Tag.php
Labels: enhancement

#87 Feat/mail
  config/common.ini.tmpl
  src/Controller/Mail.php
  src/Lib/Assert/Text.php
  src/Lib/Mailer/Headers.php
  src/Lib/Mailer/Mail.php
Labels: enhancement

#93 Fixed minor bugs
  .github/workflows/test.yml
  bin/install.sh
  composer.json
  composer.lock
  src/Bootstrap.php
  src/Controller/Gallery.php
  src/Controller/Image.php
  src/Lib/FileSystem/File.php
  src/Lib/FileSystem/Image.php
  src/Model/Entity/Gallery.php
  src/Model/Entity/Image.php
  src/View/Json.php
Labels: bug, enhancement

#102 Remove vscode folder
  .gitignore
  .vscode/launch.json
Labels: chore

#104 FIxed typo
  .github/pull_request_template.md
Labels: bug, chore

#106 Reformat issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#103 Added local config file overwrites
  .gitignore
  bin/install.sh
  config/common.ini
  src/Lib/Configuration/ConfigurationFactory.php
Labels: chore
